package ca.cgjennings.apps.arkham.plugins.engine;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Arrays;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;
import java.util.concurrent.atomic.AtomicLong;
import org.mozilla.javascript.Context;
import org.mozilla.javascript.Script;

/**
 * Process-wide cache of compiled Rhino {@link Script} objects keyed by
 * source hash plus filename and the compilation flags that affect the
 * generated bytecode. Strange Eons creates one script engine per
 * component / sheet / tile, and every engine independently re-evaluates
 * the same handful of bootstrap libraries (bootstrap, common,
 * backwards-compatibility, imageutils, ...). Caching the compiled form
 * lets each engine reuse the already-parsed bytecode instead of paying
 * the parse + compile cost on every invocation.
 *
 * <p>{@link Script} instances are documented as safe to invoke against
 * any compatible scope, so a single compiled instance can be exec'd
 * concurrently from multiple component scopes without further
 * synchronization.
 */
public final class CompiledScriptCache {

    private static final ConcurrentMap<Key, Script> cache = new ConcurrentHashMap<>();
    private static final AtomicLong hits = new AtomicLong();
    private static final AtomicLong misses = new AtomicLong();

    private CompiledScriptCache() {
    }

    /**
     * Returns a compiled {@link Script} for the given source, compiling
     * it on the first request and reusing the cached instance on
     * subsequent requests with the same source/filename/flags.
     *
     * @param cx the entered Rhino context to compile under
     * @param source full script source text
     * @param filename name reported in errors and stack traces; also part of the cache key
     */
    public static Script getOrCompile(Context cx, String source, String filename) {
        Key key = keyFor(source, filename, cx);
        Script existing = cache.get(key);
        if (existing != null) {
            hits.incrementAndGet();
            return existing;
        }
        Script compiled = cx.compileString(source, filename, 1, null);
        Script previous = cache.putIfAbsent(key, compiled);
        if (previous != null) {
            // racing thread won; reuse its instance
            hits.incrementAndGet();
            return previous;
        }
        misses.incrementAndGet();
        return compiled;
    }

    public static long hits() {
        return hits.get();
    }

    public static long misses() {
        return misses.get();
    }

    public static int size() {
        return cache.size();
    }

    private static Key keyFor(String source, String filename, Context cx) {
        byte[] hash = sha256(source);
        int optLevel = cx.getOptimizationLevel();
        boolean warningsAreErrors = SEScriptEngineFactory.getWarningsAreTreatedAsErrors();
        return new Key(filename, hash, optLevel, warningsAreErrors);
    }

    private static byte[] sha256(String s) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            return md.digest(s.getBytes(StandardCharsets.UTF_8));
        } catch (NoSuchAlgorithmException e) {
            throw new AssertionError("SHA-256 not available", e);
        }
    }

    private static final class Key {
        final String filename;
        final byte[] hash;
        final int optLevel;
        final boolean warningsAreErrors;
        private final int hashCode;

        Key(String filename, byte[] hash, int optLevel, boolean warningsAreErrors) {
            this.filename = filename;
            this.hash = hash;
            this.optLevel = optLevel;
            this.warningsAreErrors = warningsAreErrors;
            int h = filename.hashCode();
            h = 31 * h + Arrays.hashCode(hash);
            h = 31 * h + optLevel;
            h = 31 * h + (warningsAreErrors ? 1 : 0);
            this.hashCode = h;
        }

        @Override
        public boolean equals(Object o) {
            if (!(o instanceof Key)) {
                return false;
            }
            Key k = (Key) o;
            return optLevel == k.optLevel
                    && warningsAreErrors == k.warningsAreErrors
                    && filename.equals(k.filename)
                    && Arrays.equals(hash, k.hash);
        }

        @Override
        public int hashCode() {
            return hashCode;
        }
    }
}
